mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"
urlpatterns = [
    path('', views.home, name='home'),
    path('movie-search/', views.search_movies, name='movie_search'),
    path('user-search/', views.search_users, name='user_search'),
    path('logout/', views.handle_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('add-watchlist/<int:movie_id>/<path:next>', views.add_watchlist, name='add_watchlist'),
    path('add-watched/<int:movie_id>/<path:next>', views.add_watched, name='add_watched'),
    path('create-account/', views.create_account, name='create_account'),
    path('user/<str:usr>/', views.list_user_reviews, name='view_user'),
    path('movie/<int:movie_id>/', views.list_movie_reviews, name='view_movie'),
    path('new-review/<int:movie_id>/', views.new_review, name='new_review'),
    path('review/<int:movie_id>+<str:usr>/', views.view_review, name='view_review'),
    path('edit-review/<int:movie_id>/', views.edit_review, name='edit_review'),
    path('delete-review/<int:movie_id>/', views.delete_review, name='delete_review'),
]

moviedb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User


class SiteAdmin(models.Model):
    user = models.ForeignKey(User, related_name='siteadmin', on_delete=models.CASCADE)

mainapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from mainapp import db_utils

@login_required
def home(request): # user home page (reviews, watched, watchlist)
    user = request.user

    reviews = db_utils.get_reviews_by_user(user)
    movies = []
    for review in reviews:
        movies.append(db_utils.get_movie(review[0]))

    watchlist = db_utils.get_watchlist(user)

    watched = db_utils.get_watched(user)

    return render(request, 'mainapp/home.html', {"email": user, "reviews":reviews, "movies":movies, "watchlist": watchlist, "watched": watched})

def user_login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('mainapp:home')
        
        return render(request, 'mainapp/login.html', {'errormsg': 'Incorrect email or password'})

    return render(request, 'mainapp/login.html')

def create_account(request):
    if request.method == "POST":
        email = request.POST.get("email")
        name = request.POST.get('name')
        number = request.POST.get("phone number")
        password = request.POST.get("password")

        hashed_password = make_password(password)

        success = db_utils.add_user(email, name, number, hashed_password)

        if not success:
            return render(request, 'mainapp/create_account.html', {'errormsg': 'email already exists'})
        
        user = authenticate(request, username=email, password=password)
        login(request, user)

        return redirect('mainapp:home')
    
    return render(request, 'mainapp/create_account.html')

def handle_logout(request):
    logout(request)
    return redirect('mainapp:login')

@login_required
def search_movies(request):
    movies = []

    if request.method == "POST":
        title = request.POST.get("title")
        min_score = request.POST.get("min_score")

        if len(min_score) == 0: min_score = None

        movies = db_utils.get_movies_full(title, min_score, get_watched=request.user.email, get_watchlist=request.user.email, get_reviewed=request.user.email)
        

    scores = list(range(0, 101))[::-1]
    scores = [x/10 for x in scores]

    return render(request, 'mainapp/search_movies.html', context={'scores': scores, 'movies': movies})

@login_required
def add_watchlist(request, movie_id, next):
    db_utils.add_movie_to_watchlist(request.user.email, movie_id)
    return redirect(next)

@login_required
def add_watched(request, movie_id, next):
    db_utils.add_movie_to_watched(request.user.email, movie_id)
    return redirect(next)

@login_required
def search_users(request):
    users = []

    if request.method == "POST":
        name = request.POST.get("name")
        users = db_utils.get_users(name)
        
    return render(request, 'mainapp/search_users.html', context={'users': users})

@login_required
def list_movie_reviews(request, movie_id):
    if db_utils.get_movie(movie_id) is None:
        return redirect('mainapp:home')
    
    movie = db_utils.get_movie(movie_id)
    reviews = db_utils.get_reviews_by_movie(movie_id)

    return render(request, 'mainapp/movie.html', {"reviews":reviews, "movie":movie})

@login_required
def list_user_reviews(request, usr):
    if db_utils.get_user(usr) is None:
        return redirect('mainapp:home')

    reviews = db_utils.get_reviews_by_user(usr)
    movies = []
    for review in reviews:
        movies.append(db_utils.get_movie(review[0]))

    return render(request, 'mainapp/user.html', {"reviews":reviews, "movies":movies})

@login_required
def list_user_watchlist(request):
    pass

@login_required
def new_review(request, movie_id):
    if db_utils.get_movie(movie_id) is None:
        return redirect('mainapp:home')
    
    movie = db_utils.get_movie(movie_id)

    if request.method == "POST":
        db_utils.add_review(movie_id, request.user, request.POST.get("score"), 
                            request.POST.get("reviewTitle"), request.POST.get("written-review"))
        return redirect('mainapp:home')

    return render(request, 'mainapp/new_review.html', {"movie": movie})

def view_review(request, movie_id, usr):
    review = db_utils.get_review(movie_id, usr)
    movie = db_utils.get_movie(movie_id)

    if str(request.user) == str(usr):
        allow_edit = True
    else:
        allow_edit = False

    return render(request, 'mainapp/view_review.html', {"review":review, "movie":movie, "allow_edit":allow_edit})
    


@login_required
def delete_review(request, movie_id):
    db_utils.delete_review(movie_id, request.user)
    return redirect('mainapp:home')

@login_required
def edit_review(request, movie_id):
    usr = request.user
    movie = db_utils.get_movie(movie_id)

    review = db_utils.get_review(movie_id, usr)

    if review is None:
        return redirect(reverse('mainapp:new_review', args=[movie_id]))

    if request.method == "POST":
        db_utils.update_review(movie_id, usr, request.POST.get("score"), 
                            request.POST.get("reviewTitle"), request.POST.get("written-review"))
        return redirect('mainapp:home')
    
    return render(request, 'mainapp/edit_review.html', {"movie": movie})

mainapp/templates/mainapp/create_account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Create Account</title>
</head>
<body>
    <div class="box">
        <div class="container">
    
            <div class="top">
                <header>MovieDB</header>
            </div>
            
            <form class="login" method="POST" action="{% url 'mainapp:create_account' %}">
                {% csrf_token %}

                <!-- Email Field -->
                <div class="input-field">
                    <input type="text" class="input" name="email" required placeholder="Email" id="id_login">
                    <i class='bx bx-user' ></i>
                </div>

                <!-- Name Field -->
                <div class="input-field">
                    <input type="text" class="input" name="name" required placeholder="Name" id="id_name">
                    <i class='bx bx-user' ></i>
                </div>

                <!-- Phone Number Field -->
                <div class="input-field">
                    <input type="tel" class="input" name="phone number" required placeholder="Phone Number" id="id_phone_number">
                    <i class='bx bx-user' ></i>
                </div>
        
                <!-- Password Field -->
                <div class="input-field">
                    <input type="Password" class="input" name="password" required placeholder="Password" id="id_password">
                    <i class='bx bx-lock-alt'></i>
                </div>

                <input type="submit" class="regular-login" value="Create Account" id="">
            </form> 
            <div style="color: red;">
                {% if errormsg %}
                    {{ errormsg }}
                {% endif %}
            </div>

            <a href="{%url 'mainapp:login' %}">Or Login</a>
        </div>
    </div> 
</body>
</html>

mainapp/templates/mainapp/edit_review.html
{% include "nav.html" %}
{% load static %}
<!DOCTYPE html>
<html>
    <div class="d-flex justify-content-center">
        <header><b>Edit Review for "{{ movie.1 }}" </b></header>
    </div>
    <form class="container" action="{% url 'mainapp:edit_review' movie.0 %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="Review Title">Review Title</label>
          <input type="reviewTitle" class="form-control" name="reviewTitle" id="reviewTitle" aria-describedby="reviewHelp" placeholder="Enter review title">
        </div>
        <div class="form-group">
          <label for="Score">Score</label>
          <input type="score" class="form-control" name="score" id="score" placeholder="Enter score">
        </div>
        <div class="form-group">
            <label for="written-review">Written Review</label>
          <textarea class="form-control" name="written-review" id="written-review" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</html>

mainapp/templates/mainapp/home.html
{% include "nav.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ email }}</title>
    <div class="d-flex justify-content-center">
        <header><b> {{ email }} </b></header>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-sm">
            <title>Reviews</title>
            <header>My Reviews:</header>
            {% block content %}
            <table class="table table-striped position-static">
                <thead>
                <tr>
                    <th scope="col">Movie Title</th>
                    <th scope="col">Score</th>
                    <th scope="col">Review Title</th>
                    <th scope="col">Review</th>
                </tr>
                </thead>
                <tbody>
                {% for movie in movies %}
                    {% for review in reviews %}
                        {% if movie.0 == review.0 %}
                        <tr>
                            <th scope ="row">
                                <a href="{% url 'mainapp:view_review' movie.0 review.1 %}">
                                {{ movie.1 }}
                                </a>
                            </th>
                            <td style="max-width: 250px;">{{ review.2 }}</td>
                            <td style="max-width: 250px;">{{ review.3 }}</td>
                            <td class ="d-block text-truncate" style="max-width: 250px;">{{ review.4 }}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
            {% endblock %}
        </div>
          <div class="col-sm">
            <title>Watchlist</title>
            <header>Watchlist:</header>
            {% block watchlist %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Movie Title</th>
                    <th scope="col">Average Score</th>
                </tr>
                </thead>
                <tbody>
                {% for movie in watchlist %}
                        <tr>
                            <th scope ="row">{{ movie.2 }}</th>
                            <td>{{ movie.4 }}</td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endblock %}
          </div>
          <div class="col-sm">
            <title>Watched</title>
            <header>Already Watched:</header>
            {% block watched %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Movie Title</th>
                    <th scope="col">Average Score</th>
                </tr>
                </thead>
                <tbody>
                {% for movie in watched %}
                        <tr>
                            <th scope ="row">{{ movie.2 }}</th>
                            <td>{{ movie.4 }}</td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endblock %}
          </div>
        </div>
      </div>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/schedule.css' %}"> -->
</head>
<body>
</body>
</html>

mainapp/templates/mainapp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Login</title>
</head>
<body>
    <div class="box">
        <div class="container">
    
            <div class="top">
                <header>MovieDB</header>
            </div>
            
            <form class="login" method="POST" action="{% url 'mainapp:login' %}">
                {% csrf_token %}

                <!-- Email Field -->
                <div class="input-field">
                    <input type="text" class="input" name="email" required placeholder="Email" id="id_login">
                    <i class='bx bx-user' ></i>
                </div>
        
                <!-- Password Field -->
                <div class="input-field">
                    <input type="Password" class="input" name="password" required placeholder="Password" id="id_password">
                    <i class='bx bx-lock-alt'></i>
                </div>

                <input type="submit" class="regular-login" value="Login" id="">
            </form> 
            <div style="color: red;">
                {% if errormsg %}
                    {{ errormsg }}
                {% endif %}
            </div>

            <a href="{%url 'mainapp:create_account' %}">Or Create an Account</a>
        </div>
    </div> 
</body>
</html>

mainapp/templates/mainapp/movie.html
{% include "nav.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Reviews</title>
    <header><b> "{{movie.1}}" Reviews: </b></header>
    {% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">User</th>
            <th scope="col">Score</th>
            <th scope="col">Review Title</th>
            <th scope="col">Review</th>
            </tr>
        </thead>
        <tbody>
        {% for review in reviews %}
            <tr>
                <th scope ="row">
                    <a href="{% url 'mainapp:view_user' review.1 %}">
                    {{ review.1 }}
                    </a>
                </th>
                <td>{{ review.2 }}</td>
                <td>{{ review.3 }}</td>
                <td>{{ review.4 }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}
</head>
<body>

<!-- Add the Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/mainapp/search_movies.html
{% include "nav.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>Movie Search</title>
</head>
<body>
    <div>
        <br>
    
        {% block content %}
    
            <form class="container" action="{% url 'mainapp:movie_search' %}" method="post">
                {% csrf_token %}
                <!-- Title Filter -->
                <div class="col-md-4 mb-3">
                    <label for="title">Title:</label>
                    <input class="form-control" type="text" name="title" id="title">
                </div>

                <!-- Year Filter -->
                <div class="col-md-3 mb-3">
                    <label for="min_score">Minimum Score:</label>
                    <select class="form-control" name="min_score" id="min_score">
                        <option value="" selected></option>
                        {% for score in scores %}
                        <option value="{{ score }}">{{ score }}</option>
                        {% endfor %}
                    </select>
                </div>
    
                <!-- Search Button -->
                <div class="col-md-6 mb-3">
                    <button type="submit" class="btn btn-primary" name="search_button">Search</button>
                </div>
            </form>
            <hr>
    
            <br>
            <br>

            {% if movies %}
                <div class="container">
    
                    {% for movie in movies %}
                        <div class="card mb-3">
                            <div class="card-header">
    
                                <div class="row align-items-center">
                                    <div class="col-sm-auto">
                                        {{ movie.title }}
                                    </div>
                                    <div class="col-sm-auto">
                                        {{ movie.length|date:'H:i' }}
                                    </div>
                                    <div class="col-sm-auto">
                                        {{ movie.average_review_score }}
                                    </div>
    
                                    <!-- Modal for More Info -->
                                    <div class="col-auto">
                                        <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#extra_info_{{ forloop.counter }}">
                                            More Info
                                        </button>
                                    </div>
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:view_movie' movie.movie_id %}">
                                            See Reviews
                                        </a>
                                    </div>
                                    {% if movie.watched %}
                                    {% elif movie.watchlist %}
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:add_watched' movie.movie_id request.path|urlencode %}">
                                            Add to Watched
                                        </a>
                                    </div>
                                    {% else %}
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:add_watched' movie.movie_id request.path|urlencode %}">
                                            Add to Watched
                                        </a>
                                    </div>
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:add_watchlist' movie.movie_id request.path|urlencode %}">
                                            Add to Watchlist
                                        </a>
                                    </div>
                                    {% endif %}
                                    {% if movie.reviewed %}
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:edit_review' movie.movie_id %}">
                                            Edit Review
                                        </a>
                                    </div>
                                    {% else %}
                                    <div class="col-auto">
                                        <a class="btn btn-primary" type="button" href="{% url 'mainapp:new_review' movie.movie_id %}">
                                            Leave Review
                                        </a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
    
                            <div class="modal fade" id="extra_info_{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="extraInfoModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="extraInfoModalLabel">{{ movie.title }}</h5>
                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="col">
                                                <div class="sticky-top" style="position: -webkit-sticky">
                                                    <div class="card container">
                                                        <div class="card-body">
                                                            <div class="row">
                                                                Genres: {{ movie.genres }}
                                                            </div>

                                                            {% for cast in movie.cast %}
                                                            <div class="row">
                                                                {{ cast.role }}: {{ cast.name }}
                                                            </div>
                                                            {% endfor %}

                                                            {% for score in movie.musicscores %}
                                                            <div class="row">
                                                                {{ score.title }} - {{ score.composer }}
                                                            </div>
                                                            {% endfor %}

                                                            {% for award in movie.awards %}
                                                            <div class="row">
                                                                {{ award.award_name }} - {{ award.year }} : {% if award.did_win %} Won {% else %} Nominated {% endif %}
                                                            </div>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
    
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-auto">
                                    </div>
                                    
                                </div>
                            </div>
    
                            <div class="card-body collapse" id="extra_info_{{ forloop.counter }}">
                            </div>

                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <section class="section-2 text-center">
                    <p>No results found</p>
                </section>
            {% endif %}
        {% endblock %}
    </div>
    </body>
    </html>
    

mainapp/templates/mainapp/search_users.html
{% include "nav.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title>User Search</title>
</head>
<body>
    <div>
        <br>
    
        {% block content %}
    
            <form class="container" action="{% url 'mainapp:user_search' %}" method="post">
                {% csrf_token %}
                <!-- Name Filter -->
                <div class="col-md-4 mb-3">
                    <label for="name">Name:</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>

                <!-- Search Button -->
                <div class="col-md-6 mb-3">
                    <button type="submit" class="btn btn-primary" name="search_button">Search</button>
                </div>
            </form>
            <hr>
    
            <br>
            <br>

            {% if users %}
                <div class="container">
    
                    {% for user in users %}
                        <div class="card mb-3">
                            <div class="card-header">
    
                                <div class="row align-items-center">
                                    <div class="col-sm-auto">
                                        <a href="{% url 'mainapp:view_user' user.email %}">
                                            {{ user.name }}
                                        </a>
                                    </div>
                                    <div class="col-sm-auto">
                                        num_reviews: {{ user.number_reviews }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <section class="section-2 text-center">
                    <p>No results found</p>
                </section>
            {% endif %}
        {% endblock %}
    </div>
    </body>
    </html>
    

mainapp/templates/mainapp/view_review.html
{% include "nav.html" %}
{% load static %}
<!DOCTYPE html>
<html>
    <div class="d-flex justify-content-center">
        <header><b> Review for "{{ movie.1 }}" by {{review.1}} </b></header>
    </div>
        {% if allow_edit %}
        <div class="card mb-3 justify-content-center">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col-sm-auto">
                        <a href="{% url 'mainapp:edit_review' movie.0 %}">
                            Edit Review
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col-sm-auto">
                        <a href="{% url 'mainapp:delete_review' movie.0 %}">
                            Delete Review
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    
    <div class="jumbotron jumbotron-fluid">
        <div class="container justify-content-center">
          <h1 class="display-4">{{ review.3 }}</h1>
          <h2 class="dispaly-4">{{ review.2 }}</h2>
          <p class="lead">{{ review.4 }}</p>
        </div>
      </div>
</html>

mainapp/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">

            <!-- <div class="navbar-brand navb-logo">

            </div> -->

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLinks" aria-controls="navbarLinks" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarLinks">
                <ul class="navbar-nav nav-fill w-100 navb-items">
                    <!-- Home Page Link -->
                    <li class="nav-item">
                        <div class="item">
                            <a class="nav-link" href="{% url 'mainapp:home' %}">Profile</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="item">
                            <a class="nav-link" href="{% url 'mainapp:movie_search' %}">Movie Search</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div class="item">
                            <a class="nav-link" href="{% url 'mainapp:user_search' %}">User Search</a>
                        </div>
                    </li>
                    <li class="d-flex">
                        <div class="item-button">
                            <a class="nav-link" href="{% url 'mainapp:logout' %}" type="button">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>


<!-- Add the Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>